### PR TITLE
Add initial CMake support

### PR DESCRIPTION
**Pull request by pierre-aimi**
This is just to kick off proceedings and serve as a reminder when you get back @ckormanyos 
Will probably need some more commits to this PR before it's ready

### CODE REVIEW

**Comment by ckormanyos** [comment]
Hi @pierre-aimi CI has run green. I can add a CI run that actually builds with CMake and ninja within the next few days. I'd like to have such a CI job exercising this new build in the repo.

Thanks for getting the ball rolling and getting a CMake build started!

**Comment by pierre-aimi** [comment]
sounds good!

**Comment by pierre-aimi** [comment]
Sorry I just realised that the last line in that CMakefile is not cross-platform and is not really needed. It does a post-build copy of the built binary, but only looks for the windows .exe
You can happily delete this line:
```
add_custom_command(
        TARGET xxd POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy
                ${CMAKE_CURRENT_BINARY_DIR}/xxd.exe        
                ${CMAKE_SOURCE_DIR}
                )
```

**Comment by ckormanyos** [comment]
> realised that the last line in that CMakefile is not cross-platform

Handled conditionally and tested in CI via #18

Cc: @pierre-aimi

**Pull request merged**
